---
name: CI

on:
  push:

# PyCodeStyle:
#   syntax:
#   steps:
#     - run: pip install -r requirements.txt
#     - run: pycodestyle app.py

jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pip install -r requirements.txt
      - run: pylint app.py
  StaticCodeAnalysisTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: bandit app.py